# Generated by Django 2.2.9 on 2020-02-04 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('University', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advisor',
            name='ID',
        ),
    ]
